# The Essentials of NumPy

## Introducing the ND-array

In [1]:
import numpy as np

In [2]:
# The following code creates an N-dimensional array (ND-array)
x = np.array([0,1,2,3,4,5,6,7,8])

In [3]:
# The object belongs to the type 'numpy.ndarray'
print(type(x))
isinstance(x, np.ndarray)

<class 'numpy.ndarray'>


True

In [4]:
# You can "reshape" this array so that its contents can be accessed along 2 dimensions:
x = x.reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# You can utilize one of NumPys "vectorized" functions to square each entity in the array (without the need for a for-loop)
np.power(x,2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [6]:
# Lets take the mean value along the three distinct rows of our data
np.mean(x, axis=1)

array([1., 4., 7.])

In [7]:
# We can use broadcasting to raise each column of `x` to a different power:
x ** np.array([0., 1., 2.])

array([[ 1.,  1.,  4.],
       [ 1.,  4., 25.],
       [ 1.,  7., 64.]])

In [8]:
# Basic indexing allows us access to multi-dimensional slices of `x`:
x[:2,:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# Advanced indexing can be used to access all even-valued entries of `x`; let's update `x` so that all even-valued entries are multipled by -1:
x[x % 2 == 0] *= -1
x

array([[ 0,  1, -2],
       [ 3, -4,  5],
       [-6,  7, -8]])

## Accessing Data Along Multiple Dimensions in an Array

In [13]:
# A 0-D array
np.array(8)

# A 1-D array, shape-(3,)
np.array([2.3, 0.1, -9.1])

# A 2-D array, shape-(3,2)
np.array([[93, 95],[84, 100],[99, 87]])

# A 3-D array, shape-(2, 2, 2)
np.array([[[0,1],[2,3]], [[4,5],[6,7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Similar to Python's sequences, we use 0-based indices and slicing to access the content of an array. However, we must specify an index/slice
for each dimension of an array:

In [16]:
x = np.array([[[0,1],[2,3]], [[4,5],[6,7]]])
# get: sheet-0, both rows, flip order of columns
x[0,:,::-1]

array([[1, 0],
       [3, 2]])

In [ ]:
## One-dimensional Arrays
simple_array = np.array([2.3,0.1,-9.1])