In [4]:
import numpy as np

In [9]:
# The following code creates an N-dimensional array (ND-array)
x = np.array([0,1,2,3,4,5,6,7,8])

In [7]:
# The object belongs to the type 'numpy.ndarray'
print(type(x))
isinstance(x, np.ndarray)

<class 'numpy.ndarray'>


True

In [10]:
# You can "reshape" this array so that its contents can be accessed along 2 dimensions:
x = x.reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# You can utilize one of NumPys "vectorized" functions to square each entity in the array (without the need for a for-loop)
np.power(x,2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [14]:
# Lets take the mean value along the three distinct rows of our data
np.mean(x, axis=1)

array([1., 4., 7.])

In [17]:
# We can use broadcasting to raise each column of `x` to a different power:
x ** np.array([0., 1., 2.])

array([[ 1.,  1.,  4.],
       [ 1.,  4., 25.],
       [ 1.,  7., 64.]])

In [18]:
# Basic indexing allows us access to multi-dimensional slices of `x`:
x[:2,:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# Advanced indexing can be used to access all even-valued entries of `x`; let's update `x` so that all even-valued entries are multipled by -1:
x[x % 2 == 0] *= -1
x

array([[ 0,  1, -2],
       [ 3, -4,  5],
       [-6,  7, -8]])